<a href="https://colab.research.google.com/github/Paulina9555/035_pca_wine/blob/main/035_pca_wine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Spis treści:
1. [Import bibliotek](#0)
2. [Załadowanie danych](#1)
3. [Podział na zbiór treningowy i testowy](#2)
4. [Standaryzacja](#3)
5. [PCA](#4)

### <a name='0'></a> Import bibliotek

In [2]:
import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px

np.set_printoptions(precision=4, suppress=True, edgeitems=5, linewidth=200)

### <a name='1'></a> Załadowanie danych

In [4]:
df_raw = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df = df_raw.copy()
df.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [5]:
data = df.iloc[:, 1:]
target = df.iloc[:, 0]
data.head()

1     2     3     4    5     6     7     8     9     10    11    12  \
0  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [6]:
target.value_counts()

0
2    71
1    59
3    48
Name: count, dtype: int64

### <a name='2'></a> Podział na zbiór treningowy i testowy

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target)

### <a name='3'></a> Standaryzacja

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std[:5]

array([[ 0.9135, -0.7354,  1.2061,  0.0311,  2.2768,  1.0071,  0.6357,  1.1936, -0.4254,  0.1887,  1.2215,  0.5039,  1.5344],
       [-0.7862,  0.2567, -0.326 ,  0.7587, -0.6754, -1.0092, -0.2666,  2.4968, -0.3061, -1.0177, -0.5156,  0.9332, -1.3798],
       [ 0.5202,  1.3751,  0.8498,  1.0498,  0.8007, -0.9774, -1.1891,  0.6234, -0.238 ,  2.5477, -0.5602, -1.5569, -0.1761],
       [ 0.7359,  2.5909, -0.041 ,  0.1766, -0.5349, -0.5011, -1.3094,  0.9492, -0.9878, -0.2581, -0.2929, -0.8557, -0.6354],
       [ 1.4589, -0.677 ,  0.4222, -0.8421,  0.5898,  1.5628,  1.8289, -0.2725,  0.4437,  1.6631,  1.1324,  0.2463,  2.9439]])

### <a name='4'></a> PCA

In [10]:
from sklearn.decomposition import PCA

pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_std)
X_test_pca = pca.transform(X_test_std)
X_train_pca.shape

(133, 3)

In [11]:
results = pd.DataFrame(data={'explained_variance_ratio': pca.explained_variance_ratio_})
results['cumulatibe'] = results['explained_variance_ratio'].cumsum()
results['componnet'] = results.index + 1
results

explained_variance_ratio  cumulatibe  componnet
0                  0.351570    0.351570          1
1                  0.183644    0.535214          2
2                  0.121073    0.656287          3

In [12]:
X_train_pca_df = pd.DataFrame(data=np.c_[X_train_pca, y_train], columns=['pca1', 'pca2', 'pca3', 'target'])
X_train_pca_df.head()

pca1      pca2      pca3  target
0  1.825151  1.603764  1.227480     1.0
1 -1.946851 -1.670689  0.856582     2.0
2 -2.478596  2.784106  0.412266     3.0
3 -2.557570  0.580789 -0.252202     3.0
4  3.542947  2.474495 -0.563231     1.0

In [13]:
px.scatter_3d(X_train_pca_df, x='pca1', y='pca2', z='pca3', color='target',
              width=950, template='plotly_dark')

In [14]:
X_train_pca[:5]

array([[ 1.8252,  1.6038,  1.2275],
       [-1.9469, -1.6707,  0.8566],
       [-2.4786,  2.7841,  0.4123],
       [-2.5576,  0.5808, -0.2522],
       [ 3.5429,  2.4745, -0.5632]])

In [15]:
X_test_pca[:5]

array([[-0.6883, -2.2988,  1.0465],
       [-2.7464,  2.9076, -0.6953],
       [-3.7079,  1.9396, -0.1135],
       [ 0.6122, -1.4449,  0.6492],
       [ 1.1291, -0.0907, -1.3875]])